# Generated by Django 3.2.6 on 2022-04-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
