# Generated by Django 3.2.6 on 2022-04-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO address_addressmodel VALUES (2, '<em>23 4th Avenue NE, Crosby,nd, 58330  United States</em>')"),
        migrations.RunSQL("INSERT INTO address_addressmodel VALUES (3, '<em>33 Walter Nightingale Place, Waldwick,nj, 3463  United States</em>')"),
        migrations.RunSQL("INSERT INTO address_addressmodel VALUES (4, '<b>20 N S Street, Fort Smith,ar, 32904  United States</b>')"),
        migrations.RunSQL("INSERT INTO address_addressmodel VALUES (5, '<em>8 N Ellsworth Road, Box Elder,sd, 53319  United States</em>')"),
        migrations.RunSQL("INSERT INTO address_addressmodel VALUES (6, '<b>25 Race Street, Newark,de, 19311  United States</b>')")
    ]
